### ISSUE TITLE
Composer package not found/existing

### ISSUE THREAD

**Issue by Hans-Oleander** [SemanticMediaWiki/SemanticWatchlist#34]
The suggested composer command for installation does not work.

**Comment by JeroenDeDauw** [comment]
The command in the README will work for the 1.0 release. That release has not happened yet though. Not sure what the deal with that is. Ping @mwjames

**Comment by mwjames** [comment]
> Not sure what the deal with that is. Ping @mwjames

Hasn't been on my priority list and there are a bunch of tests missing before 1.0 is worth the label.

**Comment by JeroenDeDauw** [comment]
Do you object to doing a 1.0 release before more tests are added? Is master not already better than the 0.2.2 release?

**Comment by mwjames** [comment]
> Do you object to doing a 1.0 release before more tests are added? Is master not already better than the 0.2.2 release?

Citing http://semver.org/ with "Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes." therefore doing something like 0.5 seems to be OK but I'm not sure about 1.0.

**Comment by JeroenDeDauw** [comment]
What "the public API" is depends on who the users of your component are. Since this is a MediaWiki extension, which is not primarily meant to be used as a library, this is the functionality exposed to the end user. If you think that is still in alpha stage stability wise, then it should not be 1.0. And note that with "stability" I mean "will not change how it works", and not a measure of how few defects there are. If there are defects found, even serious ones, they can simply go into a 1.0.1 release.

**Comment by mwjames** [comment]
>  If you think that is still in alpha stage stability wise, then it should not be 1.0. And note that with "stability" I mean "will not change how it works", and not a measure of how few defects there are. If there are defects found, even serious ones, they can simply go into a 1.0.1 release.

Under the aspect of functionality (not stability) then yes this package is somewhat defined in what is supposed to be expected (besides the large list of open issue) therefore no real agruments against 1.0.

**Comment by JeroenDeDauw** [comment]
Ok, created #36
